server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ggtournament?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: josdargo
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

appDescription: "GG Tournament"
appVersion: "1.0.0"

#swagger http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /index.html
logging:
  level:
    org.springframework.security.web.*: debug